### ISSUE TITLE
Homepage content breakpoints

### ISSUE THREAD

**Issue by adamkirkwood** [ibm-apiconnect/getting-started-archive#12]
![screen shot 2017-01-05 at 2 25 55 pm](https://cloud.githubusercontent.com/assets/52746/21699980/f0e8965e-d352-11e6-852d-28b458ba03f5.png)

![screen shot 2017-01-05 at 2 26 01 pm](https://cloud.githubusercontent.com/assets/52746/21699983/f4a91750-d352-11e6-97fc-1f3998f2bbd9.png)

The cards would be better served if we created a content breakpoint to allow for 2-up between 990px-1200px.

**Comment by siddhipai** [comment]
Please Refer https://github.com/ibm-apiconnect/getting-started/pull/14
